const languages = ['html', 'css', 'javascript', 'react', 'node', 'postgres'];
console.log(languages);
var firstElement = 'the first element of the array is ' + languages[0];
console.log(firstElement);
var thirdElement = 'the 3rd element of the array is ' + languages[2];
console.log(thirdElement);
var length = 'The length of the array is ' + languages.length;
console.log(length);
var lastElement = languages[languages.length - 1];
console.log('The last element of the array is ' + lastElement);
